[workspace]
members = ["lib"]

[package]
name = "last-legend-dob-tool"
version = "0.1.0"
authors = ["Octavia Togami <octavia.togami@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[[bin]]
name = "lldob"
path = "src/main.rs"

[profile.release]
incremental = true
lto = "thin"

[dependencies]
owo-colors = "3.3.0"
supports-color = "1.3.0"
log = "0.4.16"
env_logger = "0.9.0"
rayon = "1.5.2"
last-legend-dob = { path = "./lib" }

[dependencies.clap]
version = "3.1.12"
features = ["derive"]

[dependencies.strum]
version = "0.24.0"
features = ["derive"]
